# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

shared: &shared
  working_directory: ~/repo

  environment:
    # Customize the JVM maximum heap limit
    MAVEN_OPTS: -Xmx3200m

  steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    - run: mvn install -DexcludedGroups=unstable

    - save_cache:
        paths:
          - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}

jobs:
  java-8:
    docker:
      - image: circleci/openjdk:8-jdk
    <<: *shared

  java-11:
    docker:
      - image: circleci/openjdk:11-jdk
    <<: *shared

  java-17:
    docker:
      - image: circleci/openjdk:17-jdk-buster
    <<: *shared

workflows:
  version: 2
  java-8-and-11:
    jobs:
      - java-8
      - java-11
      - java-17